public with sharing class TestCICD {
    public static void method() {

        System.debug('inside method 1');
    }

    // new method added
    public static void method2(){
        
    }
}

SUMMATION (Rating for each attribute x Weight of that attribute) / SUMMATION (Weights)

https://img.icons8.com/fluency/48/chat.png

https://dpa00000onw0emah.my.salesforce.com/secur/frontdoor.jsp?sid=00DPa00000ONW0eMAH!AQEAQC5_Q.Jel38.NdWluIxYO.yc4k_RGrXtGTw1U7p8rHLzi.vHtoFoqWqnCw7IFOLEXZbs7Sb9MN1_yW_yi73biN9A0XkU




  <lightning-card title="Primary Vehicle" icon-name="standard:vehicle">
    <div class="vehicle-name-box">
            <h1>{primaryVehicle.Name}</h1>
        </div>
